name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for linting
        run: pip install -r requirements/test.txt

      - name: Run Flake8
        uses: docker://registry.gitlab.com/pipeline-components/flake8:latest
        run: flake8

      - name: Run Black
        uses: docker://registry.gitlab.com/pipeline-components/black:latest
        run: black --diff --check .

  testing:
    runs-on: ubuntu-latest
    needs: linting
    strategy:
      matrix:
        env:
          - DJANGO_DEBUG=False
          - DJANGO_DEBUG=True
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          if [ "${{ matrix.env }}" = "DJANGO_DEBUG=False" ]; then
            pip install -r requirements/test.txt
          else
            pip install -r requirements/dev.txt
          fi

      - name: Run Django tests
        run: |
          cd weather_forecast
          export DJANGO_DEBUG=${{ matrix.env }}
          python manage.py test

  checking:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for migrations
        run: pip install -r requirements/prod.txt

      - name: Check migrations
        run: |
          cd weather_forecast
          python manage.py makemigrations --check --dry-run
